//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SATS.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SATS_DIALOG                 102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDR_MENU_MAIN                   129
#define IDR_MENU_APR                    130
#define IDC_CURSOR_HAND                 136
#define IDR_MENU_TRACK                  137
#define IDD_DIALOG1                     138
#define IDD_DIALOG_PWD                  138
#define IDC_SLIDER_ACC                  1000
#define IDC_BTN_FORD                    1001
#define IDC_EDIT_START_POS              1001
#define IDC_EDIT_SPEED                  1002
#define IDC_BTN_BACK                    1003
#define IDC_EDIT_GAP                    1003
#define IDC_EDIT_DISTANCE               1004
#define IDC_LIST_MSG                    1005
#define IDC_LIST2                       1006
#define IDC_STATIC_COMM                 1007
#define IDC_EDIT_STOP_POS               1007
#define IDC_EDIT_ACC                    1008
#define IDC_EDIT_POSITION               1009
#define IDC_COMBO_DM                    1010
#define IDC_COMBO_DIR                   1011
#define IDC_EDIT_SPEED_ATO              1012
#define IDC_COMBO_CAR                   1013
#define IDC_COMBO_MOD                   1014
#define IDC_COMBO_GAP                   1015
#define IDC_CHECK1                      1015
#define IDC_CHECK_SIMRUN                1015
#define IDC_COMBO_SIM                   1016
#define IDC_COMBO_HEADDIR               1016
#define IDC_BTN_GAP                     1017
#define IDC_COMBO_SIMDIR                1018
#define IDC_COMBO_STARTPOS              1019
#define IDC_BTN_POSSET                  1019
#define IDC_COMBO_TRACK                 1020
#define IDC_BTN_SET_ZERO_SPEED          1020
#define IDC_EDIT_AUTO_SPEED             1021
#define IDC_BTN_AUTO_SPEED              1022
#define IDC_COMBO_LOOP                  1023
#define IDC_BTN_POSSET2                 1023
#define IDC_BTN_STOP                    1023
#define IDC_CHECK2                      1024
#define IDC_CHECK_NOTRACK               1024
#define IDC_COMBO_CFG                   1025
#define IDC_RADIO1                      1026
#define IDC_RADIO_ESI                   1026
#define IDC_COMBO_DRVDIR                1026
#define IDC_COMBO_ESI                   1027
#define IDC_COMBO_APR                   1028
#define IDC_COMBO_DRVDIR2               1029
#define IDC_EDIT_ACC_ATO                1029
#define IDC_EDIT_SPEED_RECEIVE          1030
#define IDC_EDIT_ATO_ACC                1030
#define IDC_EDIT_PORT                   1031
#define IDC_EDIT1                       1032
#define IDC_EDIT_PWD                    1032
#define IDC_EDIT_ESI                    1032
#define IDC_STATIC_USER                 1033
#define IDC_EDIT_TIR                    1034
#define IDC_BUTTON1                     1035
#define IDC_BTN_OUTTC                   1035
#define IDC_EDIT_VER                    1036
#define IDC_EDIT_ACC_RECEIVE            1037
#define IDC_EDIT_SATS_ACC               1037
#define IDC_BTN_OUTDIR                  1038
#define IDC_CHECK3                      1039
#define IDC_CHECK_ATO_MODE              1039
#define IDC_EDIT_SPEED_ERROR            1040
#define IDC_EDIT_ACC_ERROR              1041
#define IDC_LIST1                       1042
#define IDC_LIST_VALUE                  1042
#define IDC_EDIT_ATOCOE                 1043
#define IDC_CHECK_FR                    1044
#define IDC_CHECK_MAR                   1045
#define IDC_CHECK_TIR                   1046
#define IDC_CHECK_ESI                   1047
#define ID_APR_                         32774
#define ID_TRACK_                       32776
#define ID_COMMAND_POP_BEGIN            32800
#define ID_TRACK_M0                     32801
#define ID_TRACK_M1                     32802
#define ID_TRACK_M2                     32803
#define ID_TRACK_M3                     32804
#define ID_TRACK_M4                     32805
#define ID_TRACK_M5                     32806
#define ID_TRACK_M6                     32807
#define ID_TRACK_M7                     32808
#define ID_TRACK_M8                     32809
#define ID_TRACK_M9                     32810
#define ID_TRACK_M10                    32811
#define ID_TRACK_M11                    32812
#define ID_TRACK_M12                    32813
#define ID_TRACK_M13                    32814
#define ID_TRACK_M14                    32815
#define ID_TRACK_F0                     32816
#define ID_TRACK_F1                     32817
#define ID_TRACK_F2                     32818
#define ID_TRACK_F3                     32819
#define ID_TRACK_F4                     32820
#define ID_TRACK_F5                     32821
#define ID_TRACK_F6                     32822
#define ID_TRACK_F7                     32823
#define ID_TRACK_F8                     32824
#define ID_TRACK_F9                     32825
#define ID_TRACK_DEL                    32826
#define ID_APR_MISSING                  32827
#define ID_32825                        32828
#define ID_COMMAND_POP_END              33000
#define ID_MENU_USER                    33001
#define ID_MENU_ESITEST                 33002
#define ID_MENU_SIMRUN                  33003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32835
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
